name: Benchmark

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - run: go mod tidy

    - name: Benchmark xylog
      run: go test -benchmem -run=^$ -bench . ./...

    - name: Benchmark zap
      run: |
        go get -t go.uber.org/zap/benchmarks 
        go test -benchmem -run=^$ -bench . go.uber.org/zap/benchmarks
